apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: jx
spec:
  chart:
    name: jx
    chartVersion: 2.0.399
  values:
    image:
      tag: 2.1.50
    restartPolicy: Always
    deployment:
      enabled: true
    service:
      enabled: true
    serviceaccount:
      enabled: true
    role:
      enabled: true
    clusterrole:
      enabled: true

  # When building AirGap, optional sub-charts need to be explicitly enabled so kots can bundle the image. If sub-chart is enabled by default no need to add them here.
  # Kots does not include the image unless the service is explicitly enabled during the bundle building process.
  builder: {}
