apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: jx-config
spec:
  groups:
    - name: jx_settings
      title: Jenkins-X Config
      description: Jenkins-X specific configuration options.
      items:
        - name: hosts_domain
          title: Jenkins-X Hostname
          help_text: Enter the hostname.
          type: text
          required: true
        - name: email_address
          title: Email Address
          help_text: Enter your Email Address.
          type: text
          default: email@example.com
    - name: postgresql
      title: Postgresql
      description: Postgresql
      items:
        - name: postgres_type
          type: select_one
          title: Postgresql Configuration
          default: postgres_embedded
          items:
            - name: postgres_embedded
              title: Embedded Postgres
            - name: postgres_external
              title: External Postgres
        - name: postgres_external_host
          title: Postgres Host
          when: '{{repl ConfigOptionEquals "postgres_type" "postgres_external"}}'
          type: text
          required: true
        - name: postgres_external_port
          title: Postgres Port
          when: '{{repl ConfigOptionEquals "postgres_type" "postgres_external"}}'
          type: text
          required: true
        - name: postgres_external_database
          title: Postgres Database
          when: '{{repl ConfigOptionEquals "postgres_type" "postgres_external"}}'
          type: text
          required: true
        - name: postgres_external_username
          title: Postgres Username
          when: '{{repl ConfigOptionEquals "postgres_type" "postgres_external"}}'
          type: text
          required: true
        - name: postgres_external_password_secret
          title: Postgres Password Secret
          when: '{{repl ConfigOptionEquals "postgres_type" "postgres_external"}}'
          type: text
          required: true
        - name: postgres_external_password_key
          title: Postgres Password Key
          when: '{{repl ConfigOptionEquals "postgres_type" "postgres_external"}}'
          type: text
          required: true
