apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: jx-config
spec:
  groups:
    - name: jx_settings
      title: Jenkins-X Config
      description: Jenkins-X specific configuration options.
      items:
        - name: hosts_domain
          title: Jenkins-X Hostname
          help_text: Enter the hostname.
          type: text
          required: true
        - name: pod_kind
          type: select_one
          title: Jenkins Pod Kind
          default: pod_kind_deployment
          items:
            - name: pod_kind_deployment
              title: Deployment
            - name: pod_kind_daemonset
              title: Daemonset
        - name: replica_count
          title: Replica Count
          type: text
          default: "1"
          when: repl{{ ConfigOptionEquals "pod_kind" "pod_kind_deployment"}}
    - name: rbac_settings
      title: Jenkins X K8s RBAC Settings
      description: Let Jenkins X manage K8s RBAC Settings
      items:
        - name: k8s_service_account
          title: Service Account
          help_text: Service Account
          type: bool
          default: "1"
        - name: k8s_role
          title: Role
          help_text: Role
          type: bool
          default: "1"
        - name: k8s_clusterrole
          title: Cluster Role
          help_text: Cluster Role
          type: bool
          default: "1"
    - name: jobs_settings
      title: Jenkins X K8s Jobs Settings
      description: Jenkins X K8s Jobs Settings
      items:
        - name: k8s_job
          title: Jenkins X Job
          help_text: Jenkins X Job
          type: bool
          default: "0"
        - name: k8s_cronjob
          title: Jenkins X CronJob
          help_text: Jenkins X CronJob
          type: bool
          default: "0"
